last_k_lines: last_k_lines.cpp
	g++ -std=c++11 last_k_lines.cpp -o last_k_lines

short_test: last_k_lines short_test.txt
	./last_k_lines short_test.txt 5

test: last_k_lines test.txt
	./last_k_lines test.txt 5
